project:
  type: website

website:
  title: "Bayes1@UBC"
  navbar:
    left:
      - syllabus.qmd
      - schedule.qmd
  body-header: | 
    ::: callout-caution
    This website is under construction. At this stage, information printed here may not be accurate.
    :::

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

