project:
  type: website

website:
  title: "Bayes1@UBC"
  navbar:
    left:
      - syllabus.qmd
      - schedule.qmd
      - project.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

