project:
  type: website
  resources:
    - "*.jpeg"

website:
  title: "STAT 447"
  navbar:
    logo: "bayes-black-hole.jpeg"
    background: black
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

