project:
  type: website

website:
  title: "Bayes1@UBC"
  sidebar:
    contents:
      - text: "Syllabus"
        file: syllabus.qmd
      - schedule.qmd
      - project.qmd
      - text: "---"
      - section: "Probability essentials"
        contents: 
          - auto: "w01_discrete_inference/*"
          - text: "Exercises"
            file: exercises/ex01.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

