project:
  type: website

website:
  title: "Bayes1@UBC"
  navbar:
    left:
      - text: "Syllabus"
        file: syllabus.qmd
      - schedule.qmd
      - project.qmd


format:
  html:
    include-in-header: 
      - file: macros.qmd
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

