project:
  type: website

website:
  title: "Bayes1@UBC"
  sidebar:
    contents:
      - text: "Syllabus"
        file: syllabus.qmd
      - schedule.qmd
      - project.qmd
      - text: "---"
      - section: "Introduction"
        contents: 
          - auto: "w00_intro/*"
      - section: "Probability essentials"
        contents: 
          - auto: "w01_discrete_inference/*"
          - text: "Exercises"
            file: exercises/ex01.qmd
      - section: "Bayes on a discrete model"
        contents: 
          - auto: "w02_discrete_bayes/*"
          - text: "Exercises"
            file: exercises/ex02.qmd
          - text: "Challenge"
            file: challenges/ch02.qmd
      - section: "A first look at PPLs"
        contents: 
          - auto: "w03_ppl/*"
          - text: "Exercises"
            file: exercises/ex03.qmd
          - text: "Challenge"
            file: challenges/ch03.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

