project:
  type: website

website:
  title: "Bayes1@UBC"
  sidebar:
    contents:
      - text: "Syllabus"
        file: syllabus.qmd
      - schedule.qmd
      - project.qmd
      - section: "Exercises"
        contents: exercises/*


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    linkcolor: black

editor: visual

