---
title: "Syllabus: STAT447C Bayesian Statistics"
editor: 
  mode: source
---


{{< include _announce.qmd >}}


## Course description

Bayesian inference is a flexible and powerful approach to modeling reality, making optimal predictions from data, and quantifying uncertainty in a coherent manner. Thanks to their versatility, Bayesian methods are now widely used in virtually all fields of science, engineering, and beyond.

In **STAT 447C**, you will:

-   design probabilistic models to approach real-world inferential problems;
-   perform inference using Bayesian modelling languages;
-   critically assess, debug, and iteratively improve Bayesian workflows;
-   develop and analyze custom posterior approximation machinery.

## Lecture time and place

**Lecture dates:** January 7, 2025 to April 8, 2025. [Detailed schedule](schedule.qmd)

Tuesday and Thursday, 9:30-11:00. 

## Teaching team

-   [Alexandre Bouchard-Côté (Instructor)](https://www.stat.ubc.ca/~bouchard/index.html)
-   [Nikola Surjanovic (Head TA)](https://nikola-sur.netlify.app/)
-   [Caden Hewlett (TA)](https://ca.linkedin.com/in/caden-hewlett-841558168)

## Prerequisite

-   Probability: STAT 302, MATH 302 or equivalent. I will do a review of the relevant concepts, but Bayesian statistics is entirely built on top of probability theory so prior exposure to probability is the key prerequisite for this course.
-   Basic background in linear algebra (e.g. matrix multiplication, eigenvectors) and calculus (see STAT 302's prerequisites for example)
-   Computing: we will use R in the homework and during lectures. If you know another programming language but not R, you can still take this course but be prepared to spend a bit of extra time to get familiar with the R syntax. We will have special office hours sessions at the beginning of the term to help you doing that.

Come talk to me at the end of the first lecture if you are unsure about your preparation for this course.

## Software

All software used is free and open source. Some key tools we will use:

-   [R](https://cran.r-project.org/)
-   [RStudio](https://posit.co/download/rstudio-desktop/)
-   [RStan](https://mc-stan.org/users/interfaces/rstan)

We assume you have a laptop on which you can install these tools, if not, you may be able to [borrow one from UBC library](https://services.library.ubc.ca/computers-technology/technology-borrowing/).

## Textbook

Notes will be provided and complemented with readings from the following freely available textbook:

-   *Bayesian Data Analysis, Third Edition.* Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin. [PDF freely available](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf).

Additional readings and case studies will be drawn from other textbooks that are either freely available or available within UBC VPN:

-   *Bayesian essentials with R, Second Edition*. Jean-Michel Marin and Christian Robert. [PDF available via UBC library](https://www.library.ubc.ca/). [Solution to exercises.](https://arxiv.org/pdf/1503.04662.pdf)

-   *Bayes Rules*! Alicia A. Johnson, Miles Q. Ott, Mine Dogucu. [HTML freely available](https://www.bayesrulesbook.com/preface#navigating-this-book)

-   *Doing Bayesian data analysis: a tutorial with R, JAGS, and Stan, Second Edition*. John K. Kruschke. [PDF freely available](https://nyu-cdsc.github.io/learningr/assets/kruschke_bayesian_in_R.pdf).

-   *Probability and Bayesian modeling.* Jim Albert and Jingchen Hu. [PDF/HTML/EPUB freely available](https://bayesball.github.io/BOOK/probability-a-measurement-of-uncertainty.html).

-   *Statistical Rethinking, Second Edition*. Richard McElreath. [HTML available via UBC library](https://www.library.ubc.ca/).

## Assessments

Click on each item for details.

-   Participation: 15%
    -   Weekly reading assignment: each week ask and answer one question about [the readings or lectures](schedule.qmd) on {{< var piazza >}}. (or post a private comment stating the date you came to office hour this week, or if you really do not have any question, post a comment, e.g., website you found useful to learn the material) (7%)
    -   In-class iClicker questions: only participations points (unless your score is indistinguishable from random). (8%) Setup iClicker Cloud on {{< var canvas >}}.
-   Homework: 15%
    -   Weekly.
    -   Released and submitted on {{< var canvas >}}.
-   Quizzes (2 x 20%): 40%
    -   In-class.
    -   Dates: Feb 25 and March 25
-   [Final project](project.qmd): 30%

For the reading assignment and homework, we will drop the lowest week. For the iClicker, we will automatically skip up to two missed lectures. Do not ask for additional accommodations, this is the accommodation, i.e., keep these for sick days/unforeseen circumstances. On the positive side, no need to ask for permission/provide doctor's note, this will be done automatically for everyone.

For exercise grading, I will take the $\max(\text{mean}(e_1, e_2, ...), \text{mean}(e_2, e_3, ...))$, where $e_1, e_2, e_3, \dots$ are the scores for the different exercises.
The same applies for clicker participation points.
This is in place to help a couple 
students travelling in the first week, but will be automatically applied for everyone so no need to request it.

**Update Jan 20:** since a few students still are having problem enrolling, I have added one more week to the max policy described above, 
so it is now $\max(\text{mean}(e_1, e_2, ...), \text{mean}(e_2, e_3, ...), \text{mean}(e_3, e_4, ...))$. 

Once in a while, I will post some "challenge questions". 
These are not essential for learning the material and can be skipped. 
Submit your answer at any time. 
For each that you successfully solve, a week of participation activity will be waived 
(it does not have to be the same week you submit the challenge question). 
I will not post solutions for the challenge questions.


## Policy on the use of AI tools (ChatGPT, etc)

**Update Jan 20:** effective starting tomorrow at the end of the lecture, note the following policy. 

- Piazza discussion: use of AI tools is prohibited to compose or answer questions, with the exception of spell-checking tools. 
- Homework: use of AI tools is prohibited, with the exception of spell-checking tools. 
- Quizzes: use of AI tools is impossible (closed book, pen and paper). 
- Project: if you think AI tool(s) will be used, explain the scope of their use in the project proposal. Also describe all 
  uses in the final report. 
  


## Office hours

-   Instructor office hour: Fridays, 1pm, ESB 3125.
-   TA tutorial: Thursdays, 2pm, ESB 1042.

Available by appointment if you are unable to attend drop-in hours.

## Course communication

### Announcements

Course announcements will be posted on {{< var canvas >}}.

### Questions

Use {{< var piazza >}} for questions about the material, logistics, etc. Use public posts as much as possible so that other students can learn from the discussion.

Use private piazza questions if, and only if the question is about a personal matter.
