---
title: "Exercise 2: Bayes estimator"
editor: 
  mode: source
---
  
{{< include ../_macros.qmd >}}

## Goals

- Build a probability model for a concrete example.
- Introduce the concept of Bayes estimators.

<!-- 
- Review sequential Bayes update.
-->

## Setup {#sec-setup}

This exercise is centered around the following scenario:
  
{{< include ../blocks/_delta.qmd >}}


## TODO:

- Pick a numerical value for $K$ that make the plots look nice (still discrete looking but enough to show continuity) (10?)
- Give them the numerical value for the predictive
- Maybe 1 or 2 "challenge question"
  - Implementing the credible set function
  - Invariance of updates to order


## Q.1: define a Bayesian model {#sec-q1}

In order to perform inference on the unknown quantities, we must specify how
they relate to the data; i.e., we need a *probabilistic model*.
Assume that every Delta 7925H rocket has the same probability $p$ of failing.
For simplicity, let us assume that $p$ is allowed to take values on an evenly space grid
$$
p \in \left\{\frac{k}{K}: k\in \{0,\dots,K\}\right\}
$$
for some fixed $K\in\nats$. Furthermore, we have access to a collection of
numbers $\rho_k\in[0,1]$ such that[^1]
$$
\forall k\in\{0,\dots,K\}:\ \pr\left(p=\frac{k}{K}\right) = \rho_k.
$${#eq-prior} 

[^1]: Notice that in @eq-prior we are using (small cap) $p$ as a random variable, 
      i.e. starting to move away from the probability theory capitalization 
      convention towards the Bayesian convention where the same capitalization is 
      used for both the random variable and its realization, 
      [as discussed in the first week](../w01_discrete_inference/topic03_random_variables.qmd#sec-conventions-probability-vs-bayesian).

Let $Y_i$ denote a binary variable with $Y_i=1$ encoding a success, and $Y_i=0$ a failure. 
We assume that,
conditionally on $p$, the $Y_i$'s are independent of each other.

1. What are the unknown quantities in this scenario? And what is the data?
2. Write the joint distribution of this model (use the $\sim$ notation).


## Q.2: point estimates

<!-- 

1. Give an expression for the prior predictive probability of failure for the 
next launch
$$
\pr(Y_4=1)
$$

2. Give an expression for the posterior probability
$$
\pr\left(p=\frac{k}{K}\middle| Y_1=Y_2=Y_3=0 \right)
$$

-->

In this question we will use the following prior:
$$
\rho_k \propto \frac{k}{K}\left(1-\frac{k}{K}\right).
$$ {#eq-parabola-prior} 

From now on, use $K = 20$. 

To help you answer the following question, create the two vectors: 

- `prior_probabilities` where entry $i$ containing the prior probability $\rho_{i-1}$ 
defined in Q1 (the minus one reflects the fact that R uses indexing starting at 1), and 
- `realizations`, a vector of possible realizations of $p$ in the same order, 
namely $(0, 1/K, 2/K \dots, 1)$. 

1. Plot the prior PMF. Do you think this is a reasonable prior?
Hint: use the same type of plot as used last week to [plot PMFs](../w01_discrete_inference/topic04_pmfs.qmd#sec-examples). 
2. Let $\pi_k = \pr(p = k/K | Y_{1:3} = (1, 1, 1))$ denote the posterior probabilities, for 
$k \in \{0, 1, 2, \dots, K\}$. Create a vector `posterior_probabilities` where entry $i$ is $\pi_{i-1}$. Plot the posterior PMF.
3. Write a function that computes the posterior mean and mode of $p$,
and report these values. 
Hint: you should obtain $\ex[p | Y_{1:3} = (1, 1, 1)] \approx 0.7$. 


## Q.3: Bayes action

Let $a\in\{0,1\}$ be a binary variable denoting the decision of buying the
insurance ($a=1$) or not ($a=0$).

1. Based on the problem description from [the Setup Section](#sec-setup), define a loss function $L(a, y)$ that summarizes the cost of 
having taken decision $a\in\{0,1\}$ depending on whether the next launch is successful ($y = 1$) or not ($y = 0$).
Hint: use *indicator functions* (i.e. binary functions taking either the value zero or one).
2. We now consider the expected loss under the posterior predictive distribution:
$$
\mathcal{L}(a) := \ex[L(a,Y_4)|Y_{1:3}=(1, 1, 1)] 
$$
Write $\mathcal{L}(a)$ in terms of $\pr\left(Y_4=1 \middle| Y_{1:3}=(1, 1, 1) \right)$. 
We will show in class that *in this specific model*, $\pr\left(Y_4=1 \middle| Y_{1:3}=(1, 1, 1) \right)$ 
is the same as the posterior mean, which we computed earlier to be $\approx 0.7$ for our 
choice of prior.
3. Formulate a recommendation to the owner of the satellite. 


## Q.4: Confidence sets

1. Write a function that builds the highest probability set (HPS) for any coverage
$\alpha\in[0,1]$.
2. Write a function that calculates the credible interval for any given
coverage $\alpha\in[0,1]$.
3. Compare the HPS and the credible interval for $\alpha=0.99$. Are they equal?
Explain.


## Q.5: sequential updating

Until now, we have assumed that the statistician built a single model after
observing all of the three launches. We can imagine instead that the statistician
updated its model each time a new observation from a launch was available. By
updating, we mean using the posterior $p|Y_{1:i}$ as the prior for predicting
$Y_{i+1}$.

1. Show that the posterior distribution derived via sequential updating coincides
with the one from [question 1](#sec-q1).

