---
title: "Challenge questions"
editor: 
  mode: source
---
  
{{< include ../_macros.qmd >}}

{{< include ../blocks/_challenge_header.qmd >}}

Consider the following regression model:

```stan {shortcodes=true, filename="cauchy.stan"}
{{< include cauchy.stan >}}
```

We now run it on a simple synthetic dataset (note the zeros in the design matrix):

```{r message=FALSE, warning=FALSE, results=FALSE}
suppressPackageStartupMessages(require(cmdstanr))
mod = cmdstan_model("cauchy.stan")
matrix = rbind(
  c(0.1, 0),
  c(-0.3, 0),
  c(0, 0)
)
obs = c(0.2, 0.1, -0.4)
fit = mod$sample(
  seed = 1,
  output_dir = "stan_out",
  data = list(design_matrix = matrix, observations = obs),        
  iter_sampling = 10000,
  refresh = 0
)
```

...and look at the trace plots...

```{r}
suppressPackageStartupMessages(require(bayesplot))
suppressPackageStartupMessages(require(ggplot2))
mcmc_trace(fit$draws(), pars = c("coefficients[1]", "coefficients[2]")) + theme_minimal()
```

What is going on with the second coefficient? Would you get a different behaviour if you used i.i.d. samples?